on: push
jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Testing 1!"
  test-2:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Testing 2!"
  wait:
    runs-on: ubuntu-latest
    needs: [test-1, test-2]
    environment:
      name: Testing
      url: https://example.com
    steps:
    - run: echo "Poggers"
  test-3:
    runs-on: ubuntu-latest
    needs: wait
    environment: Testing
    steps:
    - run: echo "We did it"
  test-4:
    runs-on: ubuntu-latest
    needs: wait
    environment: Testing
    steps:
    - run: echo "We did it"
