on: push
jobs:
  1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Testing 1!"
  2:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Testing 2!"
  wait:
    runs-on: ubuntu-latest
    needs: [1, 2]
    environment:
      name: Testing
      url: https://example.com
    steps:
    - run: echo "Poggers"
  3:
    runs-on: ubuntu-latest
    needs: wait
    environment: Testing
    steps:
    - run: echo "We did it"
  4:
    runs-on: ubuntu-latest
    needs: wait
    environment: Testing
    steps:
    - run: echo "We did it"
